function modifyUI(x){
	return '<section class="content">'
		+'<div class="row">'
			+'<div class="col-md-12">				'
				+'<div class="box box-primary">'
					+'<div class="box-header">'
						+'<h3 class="box-title">MODIFY BOARD</h3>'
					+'</div>					'
						+'<input type="hidden" name="page" value="">'
						+'<input type="hidden" name="perPageNum" value="">'
						+'<div class="box-body">'
							+'<div class="form-group">'
								+'<label for="exampleInputEmail1">BNO</label> '
								+'<input type="text" name="bno" class="form-control" value="'+x.bno+'" readonly="readonly">'
							+'</div>'
							+'<div class="form-group">'
								+'<label for="exampleInputEmail1">Title</label> '
								+'<input id="title" type="text" name="title" class="form-control" value="'+x.title+'">'
							+'</div>'
							+'<div class="form-group">'
								+'<label for="exampleInputPassword1">Content</label>'
								+'<textarea id="write" class="form-control" name="content" rows="3">'+x.content+'</textarea>'
							+'</div>'
							+'<div class="form-group">'
								+'<label for="exampleInputEmail1">Writer</label> '
								+'<input type="text" name="writer" class="form-control" value="'+x.writer+'" readonly="readonly">'
							+'</div>'
						+'</div>				'
					+'<div id="btns" class="box-footer">'
					+'</div>'
				+'</div>'
			+'</div>'
		+'</div>'
	+'</section>'
}