function readUI(x){
	return '<section class="content">'
      +'<div class="row">'
      +'<div class="col-md-12">    '
        +'<div class="box box-primary">'
        +'<div class="box-header">'
          +'<h3 class="box-title">READ BOARD</h3>'
        +'</div>    '
    +'<input type="hidden" name="bno" value ="">'
    +'<input type="hidden" name="page" value ="">'
    +'<input type="hidden" name="perPageNum" value ="">'
  +'<div class="box-body">'
    +'<div class="form-group">'
      +'<label for="exampleInputEmail1">Title</label>'
      +'<input type="text" name="title" class="form-control" '
         +'value="'+x.title+'" readonly="readonly">'
    +'</div>'
    +'<div class="form-group">'
      +'<label for="exampleInputPassword1">Content</label>'
      +'<textarea class="form-control"  name="content" rows="3" '
      +'readonly="readonly">'+x.content+'</textarea>'
    +'</div>'
    +'<div class="form-group">'
      +'<label for="exampleInputEmail1" >Writer</label>'
      +'<input type="text" name="writer" class="form-control" '
        +'value="'+x.writer+'" readonly="readonly">'
    +'</div>'
  +'</div>'
  +'<div id="btns" class="box-footer">'
  +'</div>  '
        +'</div>'
      +'</div> '
      +'</div>  '
    +'</section>'

}