function naviUI(){
	return '<div class="main-header has-billboard" data-reactid="6">'
	+'<a aria-label="Netflix" class="logo icon-logoUpdate active"'
		+'href="#" data-reactid="7"></a>'
	+'<ul class="tabbed-primary-navigation" role="navigation">'
		+'<li class="navigation-menu"><a class="menu-trigger" role="button"'
			+'aria-haspopup="true">메뉴</a></li>'
		+'<li class="navigation-tab"><a class="current active"'
			+'href="#">홈</a></li>'
		+'<li class="navigation-tab"><a href="#">TV 프로그램</a></li>'
		+'<li class="navigation-tab"><a href="#">영화</a></li>'
		+'<li class="navigation-tab"><a href="#">최신'
				+'등록 콘텐츠</a></li>'
		+'<li class="navigation-tab"><a href="#">내가 찜한'
				+'콘텐츠</a></li>'
	+'</ul>'
	+'<div class="secondary-navigation">'
		+'<div class="nav-element">'
			+'<div class="searchBox">'
				+'<button class="searchTab" tabindex="0" aria-label="검색"'
					+'data-uia="search-box-launcher">'
					+'<span class="icon-search"></span>'
				+'</button>'
			+'</div>'
		+'</div>'
		+'<div class="nav-element show-kids">'
			+'<a href="#">키즈</a>'
		+'</div>'
		+'<div class="nav-element">'
			+'<span class="notifications"><button class="notifications-menu"'
					+'aria-haspopup="true" aria-expanded="false" aria-label="알림">'
					+'<span class="icon-button-notification"></span><span'
						+'class="notification-pill">2</span>'
				+'</button></span>'
		+'</div>'
		+'<div class="nav-element">'
			+'<div class="account-menu-item">'
				+'<div class="account-dropdown-button">'
					+'<a href="#" role="button" tabindex="0"'
						+'aria-haspopup="true" aria-expanded="false"'
						+'aria-label="김승태&nbsp;- 계정 &amp; 설정"><span class="profile-link"'
						+'role="presentation"><img class="profile-icon"'
							+'src=""'
							+'alt=""></span></a><span class="caret" role="presentation"></span>'
				+'</div>'
			+'</div>'
		+'</div>'
	+'</div>'
+'</div>'
}